development:
  adapter: postgresql
  database: my_database_development
  pool: 5
  timeout: 5000
  username: postgres
  password: sivic 
test:
  adapter: postgresql
  database: my_database_development
  pool: 5
  timeout: 5000
  username: postgres
  password: sivic 

production:
  adapter: postgresql
  database: my_database_development
  pool: 5
  timeout: 5000
  username: postgres
  password: sivic